export const countryCodes = [
  { code: '+1', country: 'United States', flag: '🇺🇸', pattern: /^\+1\d{10}$/ },
  { code: '+1', country: 'Canada', flag: '🇨🇦', pattern: /^\+1\d{10}$/ },
  { code: '+7', country: 'Russia', flag: '🇷🇺', pattern: /^\+7\d{10}$/ },
  { code: '+20', country: 'Egypt', flag: '🇪🇬', pattern: /^\+20\d{8,10}$/ },
  { code: '+27', country: 'South Africa', flag: '🇿🇦', pattern: /^\+27\d{9}$/ },
  { code: '+30', country: 'Greece', flag: '🇬🇷', pattern: /^\+30\d{10}$/ },
  { code: '+31', country: 'Netherlands', flag: '🇳🇱', pattern: /^\+31\d{9}$/ },
  { code: '+32', country: 'Belgium', flag: '🇧🇪', pattern: /^\+32\d{8,9}$/ },
  { code: '+33', country: 'France', flag: '🇫🇷', pattern: /^\+33\d{9}$/ },
  { code: '+34', country: 'Spain', flag: '🇪🇸', pattern: /^\+34\d{9}$/ },
  { code: '+36', country: 'Hungary', flag: '🇭🇺', pattern: /^\+36\d{8,9}$/ },
  { code: '+39', country: 'Italy', flag: '🇮🇹', pattern: /^\+39\d{6,11}$/ },
  { code: '+40', country: 'Romania', flag: '🇷🇴', pattern: /^\+40\d{9}$/ },
  { code: '+41', country: 'Switzerland', flag: '🇨🇭', pattern: /^\+41\d{9}$/ },
  { code: '+43', country: 'Austria', flag: '🇦🇹', pattern: /^\+43\d{10,11}$/ },
  { code: '+44', country: 'United Kingdom', flag: '🇬🇧', pattern: /^\+44\d{10}$/ },
  { code: '+45', country: 'Denmark', flag: '🇩🇰', pattern: /^\+45\d{8}$/ },
  { code: '+46', country: 'Sweden', flag: '🇸🇪', pattern: /^\+46\d{9}$/ },
  { code: '+47', country: 'Norway', flag: '🇳🇴', pattern: /^\+47\d{8}$/ },
  { code: '+48', country: 'Poland', flag: '🇵🇱', pattern: /^\+48\d{9}$/ },
  { code: '+49', country: 'Germany', flag: '🇩🇪', pattern: /^\+49\d{10,11}$/ },
  { code: '+51', country: 'Peru', flag: '🇵🇪', pattern: /^\+51\d{9}$/ },
  { code: '+52', country: 'Mexico', flag: '🇲🇽', pattern: /^\+52\d{10}$/ },
  { code: '+53', country: 'Cuba', flag: '🇨🇺', pattern: /^\+53\d{8}$/ },
  { code: '+54', country: 'Argentina', flag: '🇦🇷', pattern: /^\+54\d{10}$/ },
  { code: '+55', country: 'Brazil', flag: '🇧🇷', pattern: /^\+55\d{10,11}$/ },
  { code: '+56', country: 'Chile', flag: '🇨🇱', pattern: /^\+56\d{9}$/ },
  { code: '+57', country: 'Colombia', flag: '🇨🇴', pattern: /^\+57\d{10}$/ },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪', pattern: /^\+58\d{10}$/ },
  { code: '+60', country: 'Malaysia', flag: '🇲🇾', pattern: /^\+60\d{9,10}$/ },
  { code: '+61', country: 'Australia', flag: '🇦🇺', pattern: /^\+61\d{9}$/ },
  { code: '+62', country: 'Indonesia', flag: '🇮🇩', pattern: /^\+62\d{9,11}$/ },
  { code: '+63', country: 'Philippines', flag: '🇵🇭', pattern: /^\+63\d{10}$/ },
  { code: '+64', country: 'New Zealand', flag: '🇳🇿', pattern: /^\+64\d{8,9}$/ },
  { code: '+65', country: 'Singapore', flag: '🇸🇬', pattern: /^\+65\d{8}$/ },
  { code: '+66', country: 'Thailand', flag: '🇹🇭', pattern: /^\+66\d{8,9}$/ },
  { code: '+81', country: 'Japan', flag: '🇯🇵', pattern: /^\+81\d{10}$/ },
  { code: '+82', country: 'South Korea', flag: '🇰🇷', pattern: /^\+82\d{9,10}$/ },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳', pattern: /^\+84\d{9,10}$/ },
  { code: '+86', country: 'China', flag: '🇨🇳', pattern: /^\+86\d{11}$/ },
  { code: '+90', country: 'Turkey', flag: '🇹🇷', pattern: /^\+90\d{10}$/ },
  { code: '+91', country: 'India', flag: '🇮🇳', pattern: /^\+91\d{10}$/ },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰', pattern: /^\+92\d{10}$/ },
  { code: '+93', country: 'Afghanistan', flag: '🇦🇫', pattern: /^\+93\d{9}$/ },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰', pattern: /^\+94\d{9}$/ },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲', pattern: /^\+95\d{8,9}$/ },
  { code: '+98', country: 'Iran', flag: '🇮🇷', pattern: /^\+98\d{10}$/ },
  { code: '+212', country: 'Morocco', flag: '🇲🇦', pattern: /^\+212\d{9}$/ },
  { code: '+213', country: 'Algeria', flag: '🇩🇿', pattern: /^\+213\d{9}$/ },
  { code: '+216', country: 'Tunisia', flag: '🇹🇳', pattern: /^\+216\d{8}$/ },
  { code: '+218', country: 'Libya', flag: '🇱🇾', pattern: /^\+218\d{9}$/ },
  { code: '+220', country: 'Gambia', flag: '🇬🇲', pattern: /^\+220\d{7}$/ },
  { code: '+221', country: 'Senegal', flag: '🇸🇳', pattern: /^\+221\d{9}$/ },
  { code: '+222', country: 'Mauritania', flag: '🇲🇷', pattern: /^\+222\d{8}$/ },
  { code: '+223', country: 'Mali', flag: '🇲🇱', pattern: /^\+223\d{8}$/ },
  { code: '+224', country: 'Guinea', flag: '🇬🇳', pattern: /^\+224\d{9}$/ },
  { code: '+225', country: 'Ivory Coast', flag: '🇨🇮', pattern: /^\+225\d{8}$/ },
  { code: '+226', country: 'Burkina Faso', flag: '🇧🇫', pattern: /^\+226\d{8}$/ },
  { code: '+227', country: 'Niger', flag: '🇳🇪', pattern: /^\+227\d{8}$/ },
  { code: '+228', country: 'Togo', flag: '🇹🇬', pattern: /^\+228\d{8}$/ },
  { code: '+229', country: 'Benin', flag: '🇧🇯', pattern: /^\+229\d{8}$/ },
  { code: '+230', country: 'Mauritius', flag: '🇲🇺', pattern: /^\+230\d{8}$/ },
  { code: '+231', country: 'Liberia', flag: '🇱🇷', pattern: /^\+231\d{8}$/ },
  { code: '+232', country: 'Sierra Leone', flag: '🇸🇱', pattern: /^\+232\d{8}$/ },
  { code: '+233', country: 'Ghana', flag: '🇬🇭', pattern: /^\+233\d{9}$/ },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬', pattern: /^\+234\d{10}$/ },
  { code: '+235', country: 'Chad', flag: '🇹🇩', pattern: /^\+235\d{8}$/ },
  { code: '+236', country: 'Central African Republic', flag: '🇨🇫', pattern: /^\+236\d{8}$/ },
  { code: '+237', country: 'Cameroon', flag: '🇨🇲', pattern: /^\+237\d{9}$/ },
  { code: '+238', country: 'Cape Verde', flag: '🇨🇻', pattern: /^\+238\d{7}$/ },
  { code: '+239', country: 'São Tomé and Príncipe', flag: '🇸🇹', pattern: /^\+239\d{7}$/ },
  { code: '+240', country: 'Equatorial Guinea', flag: '🇬🇶', pattern: /^\+240\d{9}$/ },
  { code: '+241', country: 'Gabon', flag: '🇬🇦', pattern: /^\+241\d{8}$/ },
  { code: '+242', country: 'Republic of the Congo', flag: '🇨🇬', pattern: /^\+242\d{9}$/ },
  { code: '+243', country: 'Democratic Republic of the Congo', flag: '🇨🇩', pattern: /^\+243\d{9}$/ },
  { code: '+244', country: 'Angola', flag: '🇦🇴', pattern: /^\+244\d{9}$/ },
  { code: '+245', country: 'Guinea-Bissau', flag: '🇬🇼', pattern: /^\+245\d{7}$/ },
  { code: '+246', country: 'British Indian Ocean Territory', flag: '🇮🇴', pattern: /^\+246\d{7}$/ },
  { code: '+247', country: 'Ascension Island', flag: '🇦🇨', pattern: /^\+247\d{4}$/ },
  { code: '+248', country: 'Seychelles', flag: '🇸🇨', pattern: /^\+248\d{7}$/ },
  { code: '+249', country: 'Sudan', flag: '🇸🇩', pattern: /^\+249\d{9}$/ },
  { code: '+250', country: 'Rwanda', flag: '🇷🇼', pattern: /^\+250\d{9}$/ },
  { code: '+251', country: 'Ethiopia', flag: '🇪🇹', pattern: /^\+251\d{9}$/ },
  { code: '+252', country: 'Somalia', flag: '🇸🇴', pattern: /^\+252\d{8}$/ },
  { code: '+253', country: 'Djibouti', flag: '🇩🇯', pattern: /^\+253\d{8}$/ },
  { code: '+254', country: 'Kenya', flag: '🇰🇪', pattern: /^\+254\d{9}$/ },
  { code: '+255', country: 'Tanzania', flag: '🇹🇿', pattern: /^\+255\d{9}$/ },
  { code: '+256', country: 'Uganda', flag: '🇺🇬', pattern: /^\+256\d{9}$/ },
  { code: '+257', country: 'Burundi', flag: '🇧🇮', pattern: /^\+257\d{8}$/ },
  { code: '+258', country: 'Mozambique', flag: '🇲🇿', pattern: /^\+258\d{9}$/ },
  { code: '+260', country: 'Zambia', flag: '🇿🇲', pattern: /^\+260\d{9}$/ },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬', pattern: /^\+261\d{9}$/ },
  { code: '+262', country: 'Réunion', flag: '🇷🇪', pattern: /^\+262\d{9}$/ },
  { code: '+263', country: 'Zimbabwe', flag: '🇿🇼', pattern: /^\+263\d{9}$/ },
  { code: '+264', country: 'Namibia', flag: '🇳🇦', pattern: /^\+264\d{9}$/ },
  { code: '+265', country: 'Malawi', flag: '🇲🇼', pattern: /^\+265\d{9}$/ },
  { code: '+266', country: 'Lesotho', flag: '🇱🇸', pattern: /^\+266\d{8}$/ },
  { code: '+267', country: 'Botswana', flag: '🇧🇼', pattern: /^\+267\d{8}$/ },
  { code: '+268', country: 'Eswatini', flag: '🇸🇿', pattern: /^\+268\d{8}$/ },
  { code: '+269', country: 'Comoros', flag: '🇰🇲', pattern: /^\+269\d{7}$/ },
  { code: '+290', country: 'Saint Helena', flag: '🇸🇭', pattern: /^\+290\d{4}$/ },
  { code: '+291', country: 'Eritrea', flag: '🇪🇷', pattern: /^\+291\d{7}$/ },
  { code: '+297', country: 'Aruba', flag: '🇦🇼', pattern: /^\+297\d{7}$/ },
  { code: '+298', country: 'Faroe Islands', flag: '🇫🇴', pattern: /^\+298\d{6}$/ },
  { code: '+299', country: 'Greenland', flag: '🇬🇱', pattern: /^\+299\d{6}$/ },
  { code: '+350', country: 'Gibraltar', flag: '🇬🇮', pattern: /^\+350\d{8}$/ },
  { code: '+351', country: 'Portugal', flag: '🇵🇹', pattern: /^\+351\d{9}$/ },
  { code: '+352', country: 'Luxembourg', flag: '🇱🇺', pattern: /^\+352\d{9}$/ },
  { code: '+353', country: 'Ireland', flag: '🇮🇪', pattern: /^\+353\d{9}$/ },
  { code: '+354', country: 'Iceland', flag: '🇮🇸', pattern: /^\+354\d{7}$/ },
  { code: '+355', country: 'Albania', flag: '🇦🇱', pattern: /^\+355\d{9}$/ },
  { code: '+356', country: 'Malta', flag: '🇲🇹', pattern: /^\+356\d{8}$/ },
  { code: '+357', country: 'Cyprus', flag: '🇨🇾', pattern: /^\+357\d{8}$/ },
  { code: '+358', country: 'Finland', flag: '🇫🇮', pattern: /^\+358\d{9}$/ },
  { code: '+359', country: 'Bulgaria', flag: '🇧🇬', pattern: /^\+359\d{9}$/ },
  { code: '+370', country: 'Lithuania', flag: '🇱🇹', pattern: /^\+370\d{8}$/ },
  { code: '+371', country: 'Latvia', flag: '🇱🇻', pattern: /^\+371\d{8}$/ },
  { code: '+372', country: 'Estonia', flag: '🇪🇪', pattern: /^\+372\d{7,8}$/ },
  { code: '+373', country: 'Moldova', flag: '🇲🇩', pattern: /^\+373\d{8}$/ },
  { code: '+374', country: 'Armenia', flag: '🇦🇲', pattern: /^\+374\d{8}$/ },
  { code: '+375', country: 'Belarus', flag: '🇧🇾', pattern: /^\+375\d{9}$/ },
  { code: '+376', country: 'Andorra', flag: '🇦🇩', pattern: /^\+376\d{6}$/ },
  { code: '+377', country: 'Monaco', flag: '🇲🇨', pattern: /^\+377\d{8}$/ },
  { code: '+378', country: 'San Marino', flag: '🇸🇲', pattern: /^\+378\d{10}$/ },
  { code: '+380', country: 'Ukraine', flag: '🇺🇦', pattern: /^\+380\d{9}$/ },
  { code: '+381', country: 'Serbia', flag: '🇷🇸', pattern: /^\+381\d{8,9}$/ },
  { code: '+382', country: 'Montenegro', flag: '🇲🇪', pattern: /^\+382\d{8}$/ },
  { code: '+383', country: 'Kosovo', flag: '🇽🇰', pattern: /^\+383\d{8}$/ },
  { code: '+385', country: 'Croatia', flag: '🇭🇷', pattern: /^\+385\d{8,9}$/ },
  { code: '+386', country: 'Slovenia', flag: '🇸🇮', pattern: /^\+386\d{8}$/ },
  { code: '+387', country: 'Bosnia and Herzegovina', flag: '🇧🇦', pattern: /^\+387\d{8}$/ },
  { code: '+389', country: 'North Macedonia', flag: '🇲🇰', pattern: /^\+389\d{8}$/ },
  { code: '+420', country: 'Czech Republic', flag: '🇨🇿', pattern: /^\+420\d{9}$/ },
  { code: '+421', country: 'Slovakia', flag: '🇸🇰', pattern: /^\+421\d{9}$/ },
  { code: '+423', country: 'Liechtenstein', flag: '🇱🇮', pattern: /^\+423\d{7}$/ },
  { code: '+500', country: 'Falkland Islands', flag: '🇫🇰', pattern: /^\+500\d{5}$/ },
  { code: '+501', country: 'Belize', flag: '🇧🇿', pattern: /^\+501\d{7}$/ },
  { code: '+502', country: 'Guatemala', flag: '🇬🇹', pattern: /^\+502\d{8}$/ },
  { code: '+503', country: 'El Salvador', flag: '🇸🇻', pattern: /^\+503\d{8}$/ },
  { code: '+504', country: 'Honduras', flag: '🇭🇳', pattern: /^\+504\d{8}$/ },
  { code: '+505', country: 'Nicaragua', flag: '🇳🇮', pattern: /^\+505\d{8}$/ },
  { code: '+506', country: 'Costa Rica', flag: '🇨🇷', pattern: /^\+506\d{8}$/ },
  { code: '+507', country: 'Panama', flag: '🇵🇦', pattern: /^\+507\d{8}$/ },
  { code: '+508', country: 'Saint Pierre and Miquelon', flag: '🇵🇲', pattern: /^\+508\d{6}$/ },
  { code: '+509', country: 'Haiti', flag: '🇭🇹', pattern: /^\+509\d{8}$/ },
  { code: '+590', country: 'Guadeloupe', flag: '🇬🇵', pattern: /^\+590\d{9}$/ },
  { code: '+591', country: 'Bolivia', flag: '🇧🇴', pattern: /^\+591\d{8}$/ },
  { code: '+592', country: 'Guyana', flag: '🇬🇾', pattern: /^\+592\d{7}$/ },
  { code: '+593', country: 'Ecuador', flag: '🇪🇨', pattern: /^\+593\d{8,9}$/ },
  { code: '+594', country: 'French Guiana', flag: '🇬🇫', pattern: /^\+594\d{9}$/ },
  { code: '+595', country: 'Paraguay', flag: '🇵🇾', pattern: /^\+595\d{9}$/ },
  { code: '+596', country: 'Martinique', flag: '🇲🇶', pattern: /^\+596\d{9}$/ },
  { code: '+597', country: 'Suriname', flag: '🇸🇷', pattern: /^\+597\d{7}$/ },
  { code: '+598', country: 'Uruguay', flag: '🇺🇾', pattern: /^\+598\d{8}$/ },
  { code: '+599', country: 'Curaçao', flag: '🇨🇼', pattern: /^\+599\d{7}$/ },
  { code: '+670', country: 'East Timor', flag: '🇹🇱', pattern: /^\+670\d{8}$/ },
  { code: '+672', country: 'Antarctica', flag: '🇦🇶', pattern: /^\+672\d{6}$/ },
  { code: '+673', country: 'Brunei', flag: '🇧🇳', pattern: /^\+673\d{7}$/ },
  { code: '+674', country: 'Nauru', flag: '🇳🇷', pattern: /^\+674\d{7}$/ },
  { code: '+675', country: 'Papua New Guinea', flag: '🇵🇬', pattern: /^\+675\d{8}$/ },
  { code: '+676', country: 'Tonga', flag: '🇹🇴', pattern: /^\+676\d{5}$/ },
  { code: '+677', country: 'Solomon Islands', flag: '🇸🇧', pattern: /^\+677\d{7}$/ },
  { code: '+678', country: 'Vanuatu', flag: '🇻🇺', pattern: /^\+678\d{7}$/ },
  { code: '+679', country: 'Fiji', flag: '🇫🇯', pattern: /^\+679\d{7}$/ },
  { code: '+680', country: 'Palau', flag: '🇵🇼', pattern: /^\+680\d{7}$/ },
  { code: '+681', country: 'Wallis and Futuna', flag: '🇼🇫', pattern: /^\+681\d{6}$/ },
  { code: '+682', country: 'Cook Islands', flag: '🇨🇰', pattern: /^\+682\d{5}$/ },
  { code: '+683', country: 'Niue', flag: '🇳🇺', pattern: /^\+683\d{4}$/ },
  { code: '+684', country: 'American Samoa', flag: '🇦🇸', pattern: /^\+684\d{7}$/ },
  { code: '+685', country: 'Samoa', flag: '🇼🇸', pattern: /^\+685\d{7}$/ },
  { code: '+686', country: 'Kiribati', flag: '🇰🇮', pattern: /^\+686\d{8}$/ },
  { code: '+687', country: 'New Caledonia', flag: '🇳🇨', pattern: /^\+687\d{6}$/ },
  { code: '+688', country: 'Tuvalu', flag: '🇹🇻', pattern: /^\+688\d{6}$/ },
  { code: '+689', country: 'French Polynesia', flag: '🇵🇫', pattern: /^\+689\d{8}$/ },
  { code: '+690', country: 'Tokelau', flag: '🇹🇰', pattern: /^\+690\d{4}$/ },
  { code: '+691', country: 'Micronesia', flag: '🇫🇲', pattern: /^\+691\d{7}$/ },
  { code: '+692', country: 'Marshall Islands', flag: '🇲🇭', pattern: /^\+692\d{7}$/ },
  { code: '+850', country: 'North Korea', flag: '🇰🇵', pattern: /^\+850\d{9}$/ },
  { code: '+852', country: 'Hong Kong', flag: '🇭🇰', pattern: /^\+852\d{8}$/ },
  { code: '+853', country: 'Macau', flag: '🇲🇴', pattern: /^\+853\d{8}$/ },
  { code: '+855', country: 'Cambodia', flag: '🇰🇭', pattern: /^\+855\d{8,9}$/ },
  { code: '+856', country: 'Laos', flag: '🇱🇦', pattern: /^\+856\d{8}$/ },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩', pattern: /^\+880\d{10}$/ },
  { code: '+886', country: 'Taiwan', flag: '🇹🇼', pattern: /^\+886\d{9}$/ },
  { code: '+960', country: 'Maldives', flag: '🇲🇻', pattern: /^\+960\d{7}$/ },
  { code: '+961', country: 'Lebanon', flag: '🇱🇧', pattern: /^\+961\d{8}$/ },
  { code: '+962', country: 'Jordan', flag: '🇯🇴', pattern: /^\+962\d{9}$/ },
  { code: '+963', country: 'Syria', flag: '🇸🇾', pattern: /^\+963\d{8}$/ },
  { code: '+964', country: 'Iraq', flag: '🇮🇶', pattern: /^\+964\d{10}$/ },
  { code: '+965', country: 'Kuwait', flag: '🇰🇼', pattern: /^\+965\d{8}$/ },
  { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦', pattern: /^\+966\d{9}$/ },
  { code: '+967', country: 'Yemen', flag: '🇾🇪', pattern: /^\+967\d{9}$/ },
  { code: '+968', country: 'Oman', flag: '🇴🇲', pattern: /^\+968\d{8}$/ },
  { code: '+970', country: 'Palestine', flag: '🇵🇸', pattern: /^\+970\d{9}$/ },
  { code: '+971', country: 'United Arab Emirates', flag: '🇦🇪', pattern: /^\+971\d{9}$/ },
  { code: '+972', country: 'Israel', flag: '🇮🇱', pattern: /^\+972\d{9}$/ },
  { code: '+973', country: 'Bahrain', flag: '🇧🇭', pattern: /^\+973\d{8}$/ },
  { code: '+974', country: 'Qatar', flag: '🇶🇦', pattern: /^\+974\d{8}$/ },
  { code: '+975', country: 'Bhutan', flag: '🇧🇹', pattern: /^\+975\d{8}$/ },
  { code: '+976', country: 'Mongolia', flag: '🇲🇳', pattern: /^\+976\d{8}$/ },
  { code: '+977', country: 'Nepal', flag: '🇳🇵', pattern: /^\+977\d{10}$/ },
  { code: '+992', country: 'Tajikistan', flag: '🇹🇯', pattern: /^\+992\d{9}$/ },
  { code: '+993', country: 'Turkmenistan', flag: '🇹🇲', pattern: /^\+993\d{8}$/ },
  { code: '+994', country: 'Azerbaijan', flag: '🇦🇿', pattern: /^\+994\d{9}$/ },
  { code: '+995', country: 'Georgia', flag: '🇬🇪', pattern: /^\+995\d{9}$/ },
  { code: '+996', country: 'Kyrgyzstan', flag: '🇰🇬', pattern: /^\+996\d{9}$/ },
  { code: '+998', country: 'Uzbekistan', flag: '🇺🇿', pattern: /^\+998\d{9}$/ }
];